name: macos

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-macos:
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[apple,dev]
      - name: Test (skip CUDA)
        run: |
          pytest -q -m "not cuda"
